rvm, nvm, bundler

diff --git a/Dockerfile.build b/Dockerfile.build
--- a/Dockerfile.build
+++ b/Dockerfile.build
@@ -6,27 +6,13 @@ SHELL ["/bin/bash", "-l", "-c"]
 
 RUN apt update && \
   apt upgrade -y && \
-  apt install -y sudo software-properties-common curl gnupg2
+  apt install -y sudo software-properties-common curl gnupg2 jq
 
 RUN adduser --disabled-password --gecos "" uor && \
   usermod -aG sudo uor && \
   passwd -d uor
-USER uor
 
-ONBUILD ARG RUBY_VERSION
-ONBUILD ARG RAILS_VERSION
-ONBUILD ARG BUNDLER_VERSION
-ONBUILD ARG NVM_VERSION
-ONBUILD ARG NODE_VERSION
-ONBUILD ARG NPM_VERSION
-ONBUILD ARG YARN_VERSION
-ONBUILD RUN [[ -z "$RUBY_VERSION" ]] && { echo "Arg RUBY_VERSION can't be blank."; exit 1; } || { echo "RUBY_VERSION: $RUBY_VERSION"; };
-ONBUILD RUN [[ -z "$RAILS_VERSION" ]] && { echo "Arg RAILS_VERSION can't be blank."; exit 1; } || { echo "RAILS_VERSION: $RAILS_VERSION"; };
-ONBUILD RUN [[ -z "$BUNDLER_VERSION" ]] && { echo "Arg BUNDLER_VERSION can't be blank."; exit 1; } || { echo "BUNDLER_VERSION: $BUNDLER_VERSION"; };
-ONBUILD RUN [[ -z "$NVM_VERSION" ]] && { echo "Arg NVM_VERSION can't be blank."; exit 1; } || { echo "NVM_VERSION: $NVM_VERSION"; };
-ONBUILD RUN [[ -z "$NODE_VERSION" ]] && { echo "Arg NODE_VERSION can't be blank."; exit 1; } || { echo "NODE_VERSION: $NODE_VERSION"; };
-ONBUILD RUN [[ -z "$NPM_VERSION" ]] && { echo "Arg NPM_VERSION can't be blank."; exit 1; } || { echo "NPM_VERSION: $NPM_VERSION"; };
-ONBUILD RUN [[ -z "$YARN_VERSION" ]] && { echo "Arg YARN_VERSION can't be blank."; exit 1; } || { echo "YARN_VERSION: $YARN_VERSION"; };
+USER uor
 
 ONBUILD RUN echo 'Visit https://rvm.io/rvm/install' && \
   gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && \
@@ -36,20 +22,40 @@ ONBUILD RUN echo 'Visit https://rvm.io/rvm/install' && \
   echo 'rvm_ignore_gemsets_flag=1' >> ~/.rvmrc && \
   echo 'rvm_project_rvmrc_default=1' >> ~/.rvmrc && \
   source ~/.rvm/scripts/rvm && \
-  rvm rvmrc warning ignore allGemfiles && \
+  rvm rvmrc warning ignore allGemfiles
+
+ONBUILD ARG RUBY_VERSION
+ONBUILD RUN [[ -z "$RUBY_VERSION" ]] && { echo "Arg RUBY_VERSION can't be blank."; exit 1; } || { echo "RUBY_VERSION: $RUBY_VERSION"; };
+ONBUILD RUN echo 'Visit https://www.ruby-lang.org/en/downloads/releases' && \
+  source ~/.rvm/scripts/rvm && \
   rvm install $RUBY_VERSION && \
   rvm --default use $RUBY_VERSION && \
-  gem install rails --version=$RAILS_VERSION -N && \
-  gem install bundler --version=$BUNDLER_VERSION -N
+  gem update bundler
+
+ONBUILD ARG RAILS_VERSION
+ONBUILD RUN [[ -z "$RAILS_VERSION" ]] && { echo "Arg RAILS_VERSION can't be blank."; exit 1; } || { echo "RAILS_VERSION: $RAILS_VERSION"; };
+ONBUILD RUN echo 'Visit https://rubygems.org/gems/rails/versions' && \
+  source ~/.rvm/scripts/rvm && \
+  gem install rails --version=$RAILS_VERSION -N
 
 ONBUILD RUN echo 'Visit https://github.com/nvm-sh/nvm#installing-and-updating' && \
-  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash && \
+  curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/$(curl https://api.github.com/repos/nvm-sh/nvm/releases/latest -s | jq -j .tag_name)/install.sh" | bash
+
+ONBUILD ARG NODE_VERSION
+ONBUILD RUN [[ -z "$NODE_VERSION" ]] && { echo "Arg NODE_VERSION can't be blank."; exit 1; } || { echo "NODE_VERSION: $NODE_VERSION"; };
+ONBUILD RUN echo 'Visit https://www.npmjs.com/package/node?activeTab=versions' && \
   export NVM_DIR="$HOME/.nvm" && \
   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && \
-  nvm install $NODE_VERSION && \
-  nvm use $NODE_VERSION && \
-  npm install npm@$NPM_VERSION -g && \
+  nvm install $NODE_VERSION --latest-npm && \
+  nvm use $NODE_VERSION
+
+ONBUILD ARG YARN_VERSION
+ONBUILD RUN [[ -z "$YARN_VERSION" ]] && { echo "Arg YARN_VERSION can't be blank."; exit 1; } || { echo "YARN_VERSION: $YARN_VERSION"; };
+ONBUILD RUN echo 'Visit https://www.npmjs.com/package/yarn?activeTab=versions' && \
+  export NVM_DIR="$HOME/.nvm" && \
+  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
+  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && \
   npm install yarn@$YARN_VERSION -g
 
 ONBUILD ARG AROUND_BUILD
@@ -63,10 +69,11 @@ ONBUILD RUN lsb_release -a && \
   ruby -v && \
   rails -v && \
   bundler -v && \
+  echo "gem `gem -v`" && \
   export NVM_DIR="$HOME/.nvm" && \
   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && \
-  echo "nvm `nvm -v`" && \
-  echo "npm `npm -v`" && \
+  echo "nvm `nvm --version`" && \
   echo "node `node -v`" && \
+  echo "npm `npm -v`" && \
   echo "yarn `yarn -v`"
